sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

language: scala
scala:
  - 2.12.12
#  - 2.13.3

jdk:
  - openjdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dquill.macro.log=false -Dquill.binds.log=true clean test scalastyle

after_success:
   # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm -f
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm -f


